Cadastro de Filmes/config/routes.rb
Cadastro::Application.routes.draw do
  resources :rooms

  root :to => "home#index"

end

Cadastro de Filmes/app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :description, :location, :title
end

Cadastro de Filmes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Cadastro de Filmes/app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
end
end

Cadastro de Filmes/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end
  #def buscar
     #@room = Room.order(params[:id])
     #  respond_to do |format|
       # format.html { render action: "buscar" } 
    
 # end
  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Filme Gravado Com Sucesso' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Filme Atualizado Com Sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

Cadastro de Filmes/app/helpers/application_helper.rb
module ApplicationHelper
end

Cadastro de Filmes/app/helpers/rooms_helper.rb
module RoomsHelper
end

Cadastro de Filmes/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    rel="stylesheet" type="text/css">
   
  </head>
  
  <body class="">
    <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></a>
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <a class="navbar-brand" href="">Cadastro de Filmes</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
            <%= link_to "Visualizar Filmes", rooms_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
              <%= link_to "Cadastrar Filmes", new_room_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="carousel-example-generic" data-interval="3000" class="carousel slide"
          data-ride="carousel">
            <div class="carousel-inner">
              <div class="item">
                <img src="http://localhost:3000/../img/banner-1-envision-b.jpg">
                <div class="carousel-caption">
                  <h2 class="text-primary">Os Melhores CIneastas</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Bloodborne-Personagen-Vs-Ave-Rastejante-PS4-Imagem.jpg">
                <div class="carousel-caption">
                  <h2>As Melhores Animações</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Captain-America-Shield-1920x600.jpg">
                <div class="carousel-caption">
                  <h2>Os Melhores&nbsp;Blockbusters</h2>
                  <p></p>
                </div>
              </div>
              <div class="item active">
                <img src="http://localhost:3000/../img/how-to-train-your-dragon.jpg__1920x600_q85_crop_subsampling-2_upscale.jpg">
                <div class="carousel-caption">
                  <h2>Os Filmes mais Emocionantes</h2>
                  <p></p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h3 contenteditable="true" class="text-primary">Os Piguins de Madasgascar</h3>
          <img src="http://localhost:3000/../img/penguinsdemadagascar_2.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">Dark Guardians</h2>
          <img src="http://localhost:3000/../img/81HSY+lhmBL.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">The Last Of Us</h2>
          <img src="http://localhost:3000/../img/the last of us 003.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
      </div>
    </div>
     <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>

</html>

Cadastro de Filmes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="utf-8">
    <title>Cadastro de Filmes</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    rel="stylesheet" type="text/css">
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </head>
  
  <body class="">
   <!-- <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></a>
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <a class="navbar-brand" href="">Cadastro de Filmes</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to "Visualizar Filmes", rooms_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to "Inicio", root_path %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="carousel-example-generic" data-interval="3000" class="carousel slide"
          data-ride="carousel">
            <div class="carousel-inner">
              <div class="item">
                <img src="http://localhost:3000/../img/banner-1-envision-b.jpg">
                <div class="carousel-caption">
                  <h2 class="text-primary">Os Melhores CIneastas</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Bloodborne-Personagen-Vs-Ave-Rastejante-PS4-Imagem.jpg">
                <div class="carousel-caption">
                  <h2>As Melhores Animações</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Captain-America-Shield-1920x600.jpg">
                <div class="carousel-caption">
                  <h2>Os Melhores&nbsp;Blockbusters</h2>
                  <p></p>
                </div>
              </div>
              <div class="item active">
                <img src="http://localhost:3000/../img/how-to-train-your-dragon.jpg__1920x600_q85_crop_subsampling-2_upscale.jpg">
                <div class="carousel-caption">
                  <h2>Os Filmes mais Emocionantes</h2>
                  <p></p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
          </div>
        </div>
      </div>-->
        <%= yield %>
  </body>

</html>

Cadastro de Filmes/app/views/rooms/_form.html.erb
<html>
  <head>
  <title>Index</title>
   <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    rel="stylesheet" type="text/css">
    
  </head>
  <body>

 <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></a>
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <a class="navbar-brand" href="">Cadastro de Filmes</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
            <%= link_to 'Voltar', rooms_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
             <%= link_to "Inicio", root_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="carousel-example-generic" data-interval="3000" class="carousel slide"
          data-ride="carousel">
            <div class="carousel-inner">
              <div class="item">
                <img src="http://localhost:3000/../img/banner-1-envision-b.jpg">
                <div class="carousel-caption">
                  <h2 class="text-primary">Os Melhores CIneastas</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Bloodborne-Personagen-Vs-Ave-Rastejante-PS4-Imagem.jpg">
                <div class="carousel-caption">
                  <h2>As Melhores Animações</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Captain-America-Shield-1920x600.jpg">
                <div class="carousel-caption">
                  <h2>Os Melhores&nbsp;Blockbusters</h2>
                  <p></p>
                </div>
              </div>
              <div class="item active">
                <img src="http://localhost:3000/../img/how-to-train-your-dragon.jpg__1920x600_q85_crop_subsampling-2_upscale.jpg">
                <div class="carousel-caption">
                  <h2>Os Filmes mais Emocionantes</h2>
                  <p></p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
          </div>
        </div>
      </div>
     <!-- <div class="row">
        <div class="col-md-4">
          <h3 contenteditable="true" class="text-primary">Os Piguins de Madasgascar</h3>
          <img src="http://localhost:3000/../img/penguinsdemadagascar_2.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">Dark Guardians</h2>
          <img src="http://localhost:3000/../img/81HSY+lhmBL.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">The Last Of Us</h2>
          <img src="http://localhost:3000/../img/the last of us 003.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
      </div>
    </div>-->
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!--<h1 align="center">Novo Filme</h1>-->
<div class="row" class="col-md-4" align="center">
  <h2 class="text-primary">Formulário</h2>
  <%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
       <h2> Novo Filme</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Filme %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Gênero %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :Descrição %><br>
    <%= f.text_area :description %>
  </div>
  <div  class="actions">
    <%= f.submit :Gravar %>
  </div>
</div>

<% end %>
</body>
</html>

Cadastro de Filmes/app/views/rooms/buscar.html.erb

<%= render 'form' %>

Cadastro de Filmes/app/views/rooms/edit.html.erb
<%= render 'form' %>

Cadastro de Filmes/app/views/rooms/index.html.erb
<html>
  <head>
  <title>Index</title>
   <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    rel="stylesheet" type="text/css">
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </head>
  <body>

 <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></a>
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <a class="navbar-brand" href="">Cadastro de Filmes</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
            <%= link_to 'Novo Filme', new_room_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
             <%= link_to "Inicio", root_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="carousel-example-generic" data-interval="3000" class="carousel slide"
          data-ride="carousel">
            <div class="carousel-inner">
              <div class="item">
                <img src="http://localhost:3000/../img/banner-1-envision-b.jpg">
                <div class="carousel-caption">
                  <h2 class="text-primary">Os Melhores CIneastas</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Bloodborne-Personagen-Vs-Ave-Rastejante-PS4-Imagem.jpg">
                <div class="carousel-caption">
                  <h2>As Melhores Animações</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Captain-America-Shield-1920x600.jpg">
                <div class="carousel-caption">
                  <h2>Os Melhores&nbsp;Blockbusters</h2>
                  <p></p>
                </div>
              </div>
              <div class="item active">
                <img src="http://localhost:3000/../img/how-to-train-your-dragon.jpg__1920x600_q85_crop_subsampling-2_upscale.jpg">
                <div class="carousel-caption">
                  <h2>Os Filmes mais Emocionantes</h2>
                  <p></p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
          </div>
        </div>
      </div>
    <!--  <div class="row">
        <div class="col-md-4">
          <h3 contenteditable="true" class="text-primary">Os Piguins de Madasgascar</h3>
          <img src="http://localhost:3000/../img/penguinsdemadagascar_2.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">Dark Guardians</h2>
          <img src="http://localhost:3000/../img/81HSY+lhmBL.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">The Last Of Us</h2>
          <img src="http://localhost:3000/../img/the last of us 003.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
      </div>
    </div>-->
<h1 align="center">Lista de Filmes</h1>
<div class="container">
      <div class="row">
        <div class="col-md-12">
          <table class="table" align="center">
            <thead>
              <tr>
           <th>Filme</th>
           <th>Gênero</th>
          <th>Descrição</th>
          <th></th>
          <th></th>
          <th></th>
            </tr>
           </thead>
   <tbody>
<% @rooms.each do |room| %>
  <tr>
    <td><%= room.title %></td>
    <td><%= room.location %></td>
    <td><%= room.description %></td>
    <td><%= link_to 'Mostrar', room %></td>
    <td><%= link_to 'Editar', edit_room_path(room) %></td>
    <td><%= link_to 'Apagar', room, method: :delete, data: { confirm: 'Deseja Excluir Filme ?' } %></td>
  </tr>
        </tr>
            </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>

<br />

<!--<%= link_to 'Novo Filme', new_room_path %><br>
<%= link_to "Inicio", root_path %>-->
</body>
</html>

Cadastro de Filmes/app/views/rooms/new.html.erb
<%= render 'form' %>

Cadastro de Filmes/app/views/rooms/show.html.erb
<html>
  
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    rel="stylesheet" type="text/css">
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </head>
  
  <body class="">
    <div class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></a>
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <a class="navbar-brand" href="">Cadastro de Filmes</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
           <%= link_to 'Editar', edit_room_path(@room) %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
             <%= link_to 'Voltar', rooms_path %><br>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="carousel-example-generic" data-interval="3000" class="carousel slide"
          data-ride="carousel">
            <div class="carousel-inner">
              <div class="item">
                <img src="http://localhost:3000/../img/banner-1-envision-b.jpg">
                <div class="carousel-caption">
                  <h2 class="text-primary">Os Melhores CIneastas</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Bloodborne-Personagen-Vs-Ave-Rastejante-PS4-Imagem.jpg">
                <div class="carousel-caption">
                  <h2>As Melhores Animações</h2>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <img src="http://localhost:3000/../img/Captain-America-Shield-1920x600.jpg">
                <div class="carousel-caption">
                  <h2>Os Melhores&nbsp;Blockbusters</h2>
                  <p></p>
                </div>
              </div>
              <div class="item active">
                <img src="http://localhost:3000/../img/how-to-train-your-dragon.jpg__1920x600_q85_crop_subsampling-2_upscale.jpg">
                <div class="carousel-caption">
                  <h2>Os Filmes mais Emocionantes</h2>
                  <p></p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
          </div>
        </div>
      </div>
     <!-- <div class="row">
        <div class="col-md-4">
          <h3 contenteditable="true" class="text-primary">Os Piguins de Madasgascar</h3>
          <img src="http://localhost:3000/../img/penguinsdemadagascar_2.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">Dark Guardians</h2>
          <img src="http://localhost:3000/../img/81HSY+lhmBL.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
        <div class="col-md-4">
          <h2 class="text-primary">The Last Of Us</h2>
          <img src="http://localhost:3000/../img/the last of us 003.jpg"
          class="img-responsive">
          <a class="btn btn-primary" href="#">Ver Detalhes</a>
        </div>
      </div>
    </div>-->
 <div align="center">
 	<p id="notice"><%= notice %></p>

<p>
  <b>Filme:</b>
  <%= @room.title %>
</p>

<p>
  <b>Gênero:</b>
  <%= @room.location %>
</p>

<p>
  <b>Descrição:</b>
  <%= @room.description %>
</p>
</div>



</body>

</html>